---
subreddits:
  - name: example-list
    inherit:
    - gaming
    - memes
  - name: gaming
    add:
    - gaming
    - skyrim
    - raft
  - name: memes
    add:
    - memes
    - meme
    - dankmemes

bots:
  - name: example-bot
    subreddits: example-list
    comments: yes
    submissions: yes
