---
subreddits:
  - name: clean
    add:  
    - tidy
    - neat
  - name: dirty
    inherit:
    - clean
    add:
    - dirt

bots:
  - name: example-bot
    subreddits: dirty
    comments: no
    submissions: yes
