---
name: ci_kubot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: python-${{ matrix.python-version }} ${{ matrix.suffix }}
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Install python
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq --yes --assume-yes install python${{ matrix.python-version }}-venv

      - name: which python
        run: |
          which python
          python --version

      - name: Install poetry
        run: |
          curl -sL https://install.python-poetry.org | python - -y ${{ matrix.bootstrap-args }}
          cd package && poetry install

      - name: Run pytest
        run: make test

      - name: Build wheel
        run: make build
