---
name: ci_kubot

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: python-${{ matrix.python-version }} ${{ matrix.suffix }}
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
      fail-fast: false
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          apt install python3
          curl -sL https://install.python-poetry.org | python - -y ${{ matrix.bootstrap-args }}
          cd package && poetry install

      - name: Run pytest
        run: make test

      - name: Build wheel
        run: make build
